name: Set Commit Status
description: Post a commit status (success/failure/pending/error) via createCommitStatus
author: your-org
inputs:
  state:
    description: One of success, failure, pending, error
    required: true
  context:
    description: Commit status context (e.g. e2e/ready-to-merge)
    required: true
  description:
    description: Short description shown in the status
    required: false
    default: ""
  target_url:
    description: Optional URL to link from the status
    required: false
    default: ""
  sha:
    description: Commit SHA to set status on (defaults to PR head or GITHUB_SHA)
    required: false
    default: ""
  owner:
    description: Repository owner (defaults to current repo)
    required: false
    default: ""
  repo:
    description: Repository name (defaults to current repo)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Post status
      uses: actions/github-script@v7
      with:
        script: |
          const { default: run } = await import('${{ github.action_path }}/set-commit-status.mjs')
          return await run({ github, core, context })
      env:
        IN_STATE: ${{ inputs.state }}
        IN_CONTEXT: ${{ inputs.context }}
        IN_DESC: ${{ inputs.description }}
        IN_TARGET_URL: ${{ inputs.target_url }}
        IN_SHA: ${{ inputs.sha }}
        IN_OWNER: ${{ inputs.owner }}
        IN_REPO: ${{ inputs.repo }}

branding:
  icon: check-circle
  color: green
