name: Auto merge

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  has-labels:
    runs-on: ubuntu-latest
    if: |
      (
        contains(github.event.pull_request.labels.*.name, 'dependencies') &&
        contains(github.event.pull_request.labels.*.name, 'no build diff')
      )
    steps:
      - run: echo Found labels
  auto-merge:
    needs:
      - has-labels
    runs-on: ubuntu-latest
    steps:
      - run: gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
