name: Check build diff

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  check-build-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
