name: Check build diff

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-on-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .node-version

      - run: npm ci
      - run: npm run build
        env:
          ORIGIN: https://blog.odan.dev

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-main
          path: dist

  build-on-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .node-version

      - run: npm ci
      - run: npm run build
        env:
          ORIGIN: https://blog.odan.dev

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-current
          path: dist

  check-build-diff:
    needs:
      - build-on-main
      - build-on-current
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-main
          path: dist-main
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}-current
          path: dist-current

      - run: diff -qr dist-main dist-current
