name: E2E Status Check

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-e2e-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check for e2e-rejected label
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'e2e-rejected') }}" == "true" ]]; then
            echo "::error::Pull request has 'e2e-rejected' label. E2E tests must pass before merging."
            exit 1
          else
            echo "✅ No 'e2e-rejected' label found"
          fi
