name: E2E Status Check

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  workflow_call:
    inputs:
      e2e_status:
        description: "E2E test status (success, failure, skipped)"
        required: false
        type: string
        default: ""

permissions:
  statuses: write
  pull-requests: read

jobs:
  check-e2e-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decide gate result
        id: decide
        uses: actions/github-script@v7
        with:
          script: |
            const fromWorkflowCall = context.eventName === 'workflow_call';
            const e2eStatus = ( (context.payload?.inputs?.e2e_status) || '' ).toLowerCase();

            const labels = context.payload.pull_request?.labels?.map(l => l.name) ?? [];
            const hasRejected = labels.includes('e2e-rejected');

            let state = 'success';
            let description  = 'E2E status check passed';

            if ((fromWorkflowCall && e2eStatus === 'failure') || (!fromWorkflowCall && hasRejected)) {
              state = 'failure';
              description  = fromWorkflowCall
                ? 'E2E tests failed. E2E tests must pass before merging.'
                : "Pull request has 'e2e-rejected' label. E2E tests must pass before merging.";
            }

            return { state, description };

      - name: Post commit status (e2e/ready-to-merge)
        uses: ./.github/actions/set-commit-status
        with:
          state: ${{ steps.decide.outputs.result.state }}
          context: e2e/ready-to-merge
          description: ${{ steps.decide.outputs.result.description }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
