name: "Outdated Check"
on:
  workflow_dispatch:

jobs:
  outdated-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - run: npm ci

      - name: run outdate check
        uses: odanado/outdate-check-action@v0.0.7
        id: outdate-check
        with:
          cwd: ./

      - name: send metrics to GCP
        run: npx tsx ./src/scripts/send-metrics-to-gcp.ts
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          TOTAL_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.total-dependencies-count }}

          OUTDATED_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.outdated-dependencies-count }}
          LATEST_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.latest-dependencies-count }}

          OUTDATED_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.outdated-dependencies-percentage }}
          LATEST_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.latest-dependencies-percentage }}

          OUTDATED_MAJOR_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.outdated-major-dependencies-count }}
          OUTDATED_MINOR_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.outdated-minor-dependencies-count }}
          OUTDATED_PATCH_DEPENDENCIES_COUNT: ${{ steps.outdate-check.outputs.outdated-patch-dependencies-count }}

          OUTDATED_MAJOR_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.outdated-major-dependencies-percentage }}
          OUTDATED_MINOR_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.outdated-minor-dependencies-percentage }}
          OUTDATED_PATCH_DEPENDENCIES_PERCENTAGE: ${{ steps.outdate-check.outputs.outdated-patch-dependencies-percentage }}
